### ISSUE TITLE
Travis CI failed with Node v4, 0.12, 0.10

### ISSUE THREAD

**Issue by kbariotis** [bucaran/generator-rise#26]
Travis fails to build my repo with Node versions v4, 0.12, 0.10, while it passes with 5

```
Build system information
Build language: node_js
Build group: stable
Build dist: precise
Build image provisioning date and time
Thu Feb  5 15:09:33 UTC 2015
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
Linux Version
3.13.0-29-generic
Cookbooks Version
a68419e https://github.com/travis-ci/travis-cookbooks/tree/a68419e
GCC version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
LLVM version
clang version 3.4 (tags/RELEASE_34/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Pre-installed Ruby versions
ruby-1.9.3-p551
Pre-installed Node.js versions
v0.10.36
Pre-installed Go versions
1.4.1
Redis version
redis-server 2.8.19
riak version
2.0.2
MongoDB version
MongoDB 2.4.12
CouchDB version
couchdb 1.6.1
Neo4j version
1.9.4
RabbitMQ Version
3.4.3
ElasticSearch version
1.4.0
Installed Sphinx versions
2.0.10
2.1.9
2.2.6
Default Sphinx version
2.2.6
Installed Firefox version
firefox 31.0esr
PhantomJS version
1.9.8
ant -version
Apache Ant(TM) version 1.8.2 compiled on December 3 2011
mvn -version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)
Maven home: /usr/local/maven
Java version: 1.7.0_76, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "3.13.0-29-generic", arch: "amd64", family: "unix"
git.checkout
0.38s$ git clone --depth=50 --branch=master https://github.com/kbariotis/wsmanager.git kbariotis/wsmanager
Cloning into 'kbariotis/wsmanager'...
remote: Counting objects: 29, done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 29 (delta 8), reused 27 (delta 6), pack-reused 0
Unpacking objects: 100% (29/29), done.
Checking connectivity... done.
$ cd kbariotis/wsmanager
$ git checkout -qf 190666d452eaa7102039465ac3fb72244d4e3a35
This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.
If you require sudo, add 'sudo: required' to your .travis.yml
See http://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.
4.35s$ nvm install v4
######################################################################## 100.0%
Checksums empty
Now using node v4.2.3
$ node --version
v4.2.3
$ npm --version
2.14.7
$ nvm --version
0.23.3
116.94s$ npm install 
npm WARN optional dep failed, continuing fsevents@1.0.5
> wsmanager@1.0.2 prepublish /home/travis/build/kbariotis/wsmanager
> npm run build -s
Success! All dependencies used in the code are listed in package.json
src/index.js -> dist/index.js
events.js:197
    throw new TypeError('listener must be a function');
    ^
TypeError: listener must be a function
    at SocketManager.addListener (events.js:197:11)
    at new SocketManager (index.js:12:10)
    at Object.<anonymous> (index.js:117:16)
    at Module._compile (module.js:435:26)
    at loader (/home/travis/build/kbariotis/wsmanager/node_modules/babel-cli/node_modules/babel-register/lib/node.js:130:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/travis/build/kbariotis/wsmanager/node_modules/babel-cli/node_modules/babel-register/lib/node.js:140:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v4.2.3/bin/node" "/home/travis/.nvm/versions/node/v4.2.3/bin/npm" "install"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! wsmanager@1.0.2 prepublish: `npm run build -s`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wsmanager@1.0.2 prepublish script 'npm run build -s'.
npm ERR! This is most likely a problem with the wsmanager package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build -s
npm ERR! You can get their info via:
npm ERR!     npm owner ls wsmanager
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/kbariotis/wsmanager/npm-debug.log
The command "eval npm install " failed. Retrying, 2 of 3.
> wsmanager@1.0.2 prepublish /home/travis/build/kbariotis/wsmanager
> npm run build -s
Success! All dependencies used in the code are listed in package.json
src/index.js -> dist/index.js
events.js:197
    throw new TypeError('listener must be a function');
    ^
TypeError: listener must be a function
    at SocketManager.addListener (events.js:197:11)
    at new SocketManager (index.js:12:10)
    at Object.<anonymous> (index.js:117:16)
    at Module._compile (module.js:435:26)
    at loader (/home/travis/build/kbariotis/wsmanager/node_modules/babel-cli/node_modules/babel-register/lib/node.js:130:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/travis/build/kbariotis/wsmanager/node_modules/babel-cli/node_modules/babel-register/lib/node.js:140:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v4.2.3/bin/node" "/home/travis/.nvm/versions/node/v4.2.3/bin/npm" "install"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! wsmanager@1.0.2 prepublish: `npm run build -s`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wsmanager@1.0.2 prepublish script 'npm run build -s'.
npm ERR! This is most likely a problem with the wsmanager package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build -s
npm ERR! You can get their info via:
npm ERR!     npm owner ls wsmanager
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/kbariotis/wsmanager/npm-debug.log
The command "eval npm install " failed. Retrying, 3 of 3.
> wsmanager@1.0.2 prepublish /home/travis/build/kbariotis/wsmanager
> npm run build -s
Success! All dependencies used in the code are listed in package.json
src/index.js -> dist/index.js
events.js:197
    throw new TypeError('listener must be a function');
    ^
TypeError: listener must be a function
    at SocketManager.addListener (events.js:197:11)
    at new SocketManager (index.js:12:10)
    at Object.<anonymous> (index.js:117:16)
    at Module._compile (module.js:435:26)
    at loader (/home/travis/build/kbariotis/wsmanager/node_modules/babel-cli/node_modules/babel-register/lib/node.js:130:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/travis/build/kbariotis/wsmanager/node_modules/babel-cli/node_modules/babel-register/lib/node.js:140:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v4.2.3/bin/node" "/home/travis/.nvm/versions/node/v4.2.3/bin/npm" "install"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! wsmanager@1.0.2 prepublish: `npm run build -s`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wsmanager@1.0.2 prepublish script 'npm run build -s'.
npm ERR! This is most likely a problem with the wsmanager package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build -s
npm ERR! You can get their info via:
npm ERR!     npm owner ls wsmanager
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/kbariotis/wsmanager/npm-debug.log
The command "eval npm install " failed 3 times.
The command "npm install " failed and exited with 1 during .
Your build has been stopped.
```

**Comment by kbariotis** [comment]
hmm, it seems there is something wrong with my use of EventEmitter class.

sorry about that. :)

**Comment by bucaran** [comment]
No problem :+1:
