### ISSUE TITLE
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (11:0)

### ISSUE THREAD

**Issue by chrisblossom** [bucaran/generator-rise#7]
dependency-check is throwing the following error. Ideas what I am doing wrong?

index.js:
```
class newClass {
  constructor(config) {
    this.apiKey = config.apiKey;
    this.apiUser = config.apiUser;
    this.url = config.url;
  }
}

export {newClass as default};
```

error:
```
npm run build

> test-rise@1.0.0 prebuild /Users/chris/Dropbox/GitHub/test-rise
> npm run check -s && npm run clean -s

/Users/chris/Dropbox/GitHub/test-rise/node_modules/dependency-check/node_modules/detective/node_modules/acorn/dist/acorn.js:1747
  throw err;
  ^

SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (11:0)
    at Parser.pp.raise (/Users/chris/Dropbox/GitHub/test-rise/node_modules/dependency-check/node_modules/detective/node_modules/acorn/dist/acorn.js:1745:13)
    at Parser.pp.parseStatement (/Users/chris/Dropbox/GitHub/test-rise/node_modules/dependency-check/node_modules/detective/node_modules/acorn/dist/acorn.js:2450:34)
    at Parser.pp.parseTopLevel (/Users/chris/Dropbox/GitHub/test-rise/node_modules/dependency-check/node_modules/detective/node_modules/acorn/dist/acorn.js:2379:21)
    at Object.parse (/Users/chris/Dropbox/GitHub/test-rise/node_modules/dependency-check/node_modules/detective/node_modules/acorn/dist/acorn.js:101:12)
    at parse (/Users/chris/Dropbox/GitHub/test-rise/node_modules/dependency-check/node_modules/detective/index.js:10:18)
    at Function.exports.find (/Users/chris/Dropbox/GitHub/test-rise/node_modules/dependency-check/node_modules/detective/index.js:45:15)
    at module.exports (/Users/chris/Dropbox/GitHub/test-rise/node_modules/dependency-check/node_modules/detective/index.js:24:20)
    at read (/Users/chris/Dropbox/GitHub/test-rise/node_modules/dependency-check/index.js:129:22)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

**Comment by bucaran** [comment]
I couldn't reproduce this error.

#### steps I followed

+ Switch to a new `test-rise` dir.
+ Run `yo rise` and proceed with default options.
+ Added the following snippet to `src/index.js`

  ```js
class newClass {
  constructor(config) {
    this.apiKey = config.apiKey;
    this.apiUser = config.apiUser;
    this.url = config.url;
  }
}

export {newClass as default};
  ```

+ Run `npm run build`

### output

```

> test-rise@1.0.0 prebuild /Users/b/dev/test-rise
> npm run check -s && npm run clean -s

Success! All dependencies used in the code are listed in package.json

> test-rise@1.0.0 build /Users/b/dev/test-rise
> babel --optional runtime src -d dist

src/index.js -> dist/index.js

> test-rise@1.0.0 postbuild /Users/b/dev/test-rise
> npm run test -s


  testRise

/Users/b/dev/test-rise/node_modules/babel-runtime/helpers/class-call-check.js:5
    throw new TypeError("Cannot call a class as a function");
          ^
TypeError: Cannot call a class as a function
    at exports.default (/Users/b/dev/test-rise/node_modules/babel-runtime/helpers/class-call-check.js:5:11)
    at newClass (/Users/b/dev/test-rise/dist/index.js:10:3)
    at Test.<anonymous> (/Users/b/dev/test-rise/test/index.js:6:17)
    at Test.bound [as _cb] (/Users/b/dev/test-rise/node_modules/tape/lib/test.js:63:32)
    at Test.run (/Users/b/dev/test-rise/node_modules/tape/lib/test.js:76:10)
    at Test.bound [as run] (/Users/b/dev/test-rise/node_modules/tape/lib/test.js:63:32)
    at Immediate.next [as _onImmediate] (/Users/b/dev/test-rise/node_modules/tape/lib/results.js:70:15)
    at processImmediate [as _immediateCallback] (timers.js:358:17)


  total:     0
  passing:   0
  duration:  1.5s

```

Which is correct. The test will obviously fail, but all checks pass OK.

**Comment by bucaran** [comment]
I tried adding

```json
  "ecmaFeatures": {
    "modules": false
  }
```

but then I found it's ignored according to [this](
https://github.com/babel/babel-eslint/issues/53
).

**Comment by chrisblossom** [comment]
I am breaking up the class into multiple files. I ended up just using the ES5 way ( module.exports = newClass;) to export newClass without issue.

```
class newClass {
  constructor(config) {
    this.apiKey = config.apiKey;
    this.apiUser = config.apiUser;
    this.url = config.url;
  }
}

newClass.prototype.otherFunction = require('./some_file_that_exports_otherFunction');

export {newClass as default};
```

Thank you for your help.

**Comment by bucaran** [comment]
@chrisblossom Hey! Thanks for closing, but did you find a way to fix your issue and still use ES6? It seems that using ES5 would beat the purpose of this.

**Comment by chrisblossom** [comment]
@bucaran I did not find a way to fix my issue. Sorry if I prematurely closed it, I just didn't want this lingering here. Want me to reopen?

**Comment by bucaran** [comment]
Thanks. First, can you use ES6 at all? Just trying to make sure there's nothing funky in your environment.

If you can, then it's just a matter of comparing your ES6 setup against the generator perhaps?

**Comment by jonniespratley** [comment]
@chrisblossom Hello, Im also receiving this error when running the `npm run build` command.

Any thoughts?

**Comment by iamstarkov** [comment]
@jonniespratley can you describe your problem with details?
